AIRLINE_WEBSITES = {
    'AirCanada': 'https://www.aircanada.com/us/en/aco/home.html',
    'AirDo': 'https://www.airdo.jp/en/',
    'AirPremia': 'https://www.airpremia.com/us/en',
    'American': 'https://www.aa.com/homePage.do',
    'ANA': 'https://www.ana.co.jp/en/us/',
    'AsianaAirlines': 'https://flyasiana.com/C/US/EN/index',
    'ChinaAirlines': 'https://www.china-airlines.com/us/en',
    'Delta': 'https://www.delta.com/',
    'EvaAir': 'https://www.evaair.com/en-us/index.html%EF%BB%BF',
    'Hawaiian': 'https://www.hawaiianairlines.com/',
    'Ibex': 'https://www.ibexair.co.jp/en/',
    'JAL': 'https://www.jal.co.jp/jp/en/',
    'JetstarJapan': 'https://www.jetstar.com/jp/en/home?adults=1&children=0&flexible=1&flight-type=2&infants=0&origin=NRT&tab=1',
    'KoreanAir': 'https://www.koreanair.com/',
    'Peach': 'https://www.flypeach.com/en',
    'Singapore': 'https://www.singaporeair.com/en_UK/us/home#/book/bookflight',
    'Skymark': 'https://www.skymark.co.jp/en/',
    'SolaseedAir': 'https://www.solaseedair.jp/en/',
    'Spring': 'https://en.ch.com/',
    'StarflyerDomestic': 'https://www.starflyer.jp/en/',
    'StarflyerInternational': 'https://www.starflyer.jp/int_en/',
    'United': 'https://www.united.com/en/us',
    'WestJet': 'https://www.westjet.com/en-us',
    'ZipAir': 'https://www.zipair.net/en'
}